// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcWWjptDfcU2Zj6udV0-1qe-_4801hiM0',
    appId: '1:218814210827:web:9919bd29914b3418f8780e',
    messagingSenderId: '218814210827',
    projectId: 'pocketledger-c5e57',
    authDomain: 'pocketledger-c5e57.firebaseapp.com',
    storageBucket: 'pocketledger-c5e57.firebasestorage.app',
    measurementId: 'G-0XFDJJLYQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO-15POxULtoZR0BsRuJHVoX5oMmh5DpM',
    appId: '1:218814210827:android:8e5da2a1118812c6f8780e',
    messagingSenderId: '218814210827',
    projectId: 'pocketledger-c5e57',
    storageBucket: 'pocketledger-c5e57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyR6AYLkkahoDWS_b5YtpF4457k9KpnRg',
    appId: '1:218814210827:ios:41577fc88f75b3f8f8780e',
    messagingSenderId: '218814210827',
    projectId: 'pocketledger-c5e57',
    storageBucket: 'pocketledger-c5e57.firebasestorage.app',
    iosBundleId: 'com.example.pocketledger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyR6AYLkkahoDWS_b5YtpF4457k9KpnRg',
    appId: '1:218814210827:ios:41577fc88f75b3f8f8780e',
    messagingSenderId: '218814210827',
    projectId: 'pocketledger-c5e57',
    storageBucket: 'pocketledger-c5e57.firebasestorage.app',
    iosBundleId: 'com.example.pocketledger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcWWjptDfcU2Zj6udV0-1qe-_4801hiM0',
    appId: '1:218814210827:web:391696b6910de520f8780e',
    messagingSenderId: '218814210827',
    projectId: 'pocketledger-c5e57',
    authDomain: 'pocketledger-c5e57.firebaseapp.com',
    storageBucket: 'pocketledger-c5e57.firebasestorage.app',
    measurementId: 'G-2GP9NF0C49',
  );
}
