import 'package:pocketledger/services/language_service.dart';

class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Login Screen
      'welcome_back': 'Welcome Back!',
      'login_subtitle': 'Sign in to manage your finances',
      'email': 'Email',
      'email_hint': 'Enter your email',
      'password': 'Password',
      'password_hint': 'Enter your password',
      'sign_in': 'Sign In',
      'no_account': "Don't have an account? ",
      'sign_up_now': 'Sign Up Now',
      'email_required': 'Email is required',
      'password_required': 'Password is required',
      'invalid_credentials': 'Invalid email or password',
      'login_failed': 'Failed to sign in. Please try again.',
      
      // Signup Screen
      'create_account': 'Create Account',
      'signup_subtitle': 'Start your journey to financial freedom',
      'full_name': 'Full Name',
      'confirm_password': 'Confirm Password',
      'already_have_account': 'Already have an account? ',

      // Nav Bar
      'home': 'Home',
      'wallet': 'Wallet',
      'stats': 'Stats',

      // Profile Screen
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'account_settings': 'Account Settings',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'biometric_lock': 'Biometric Lock',
      'help_support': 'Help & Support',
      'about_app': 'About App',
      'log_out': 'Log Out',
      'confirm_logout': 'Confirm Logout',
      'logout_message': 'Are you sure you want to log out?',
      'cancel': 'Cancel',
      'user_details_error': 'Could not load user details',
      'account_information': 'ACCOUNT INFORMATION',
      'account_name': 'ACCOUNT NAME',
      'active_timelines': 'ACTIVE TIMELINES',
      'ai_wealth_copilot': 'AI WEALTH COPILOT',
      'amount': 'AMOUNT',
      'account_name_1': 'Account Name',
      'account_number': 'Account Number',
      'accountwise_distribution': 'Account-wise distribution',
      'accounts': 'Accounts',
      'add_card': 'Add Card',
      'add_a_credit_card': 'Add a credit card to track your balances, bills, and due dates.',
      'add_a_note': 'Add a note...',
      'add_a_savings_account': 'Add a savings account first!',
      'add_amounts_done_before': 'Add amounts done before using this app this month',
      'add_an_account_to': 'Add an account to see your assets here',
      'add_your_recurring_bills': 'Add your recurring bills, subscriptions, or utility payments and never miss a due date again.',
      'adjust_account_balance': 'Adjust Account Balance',
      'all_caught_up': 'All caught up!',
      'all_scheduled_subscriptions_and': 'All scheduled subscriptions and recurring logs combined',
      'already_paiddeducted': 'Already paid/deducted?',
      'app_locked': 'App Locked',
      'apply': 'Apply',
      'are_you_sure_you': 'Are you sure you want to delete this credit card? This action cannot be undone.',
      'are_you_sure_you_1': 'Are you sure you want to delete this recurring bill? Historical payments logged will not be deleted.',
      'available_credit': 'Available Credit',
      'available_limit': 'Available Limit',
      'bank_account_details': 'BANK ACCOUNT DETAILS',
      'branch_name': 'Branch Name',
      'card_payment': 'CARD PAYMENT',
      'combined_portfolio_balance': 'COMBINED PORTFOLIO BALANCE',
      'copy_all': 'COPY ALL',
      'card_color_theme': 'Card Color Theme',
      'card_details': 'Card Details',
      'card_network': 'Card Network',
      'card_number_eg_last': 'Card Number (e.g. last 4 digits)',
      'card_number_last_4': 'Card Number (last 4 digits or full)',
      'card_not_found': 'Card not found',
      'category': 'Category',
      'category_manager': 'Category Manager',
      'category_type': 'Category Type',
      'change': 'Change',
      'choose_how_you_want': 'Choose how you want to filter dates',
      'confirm': 'Confirm',
      'confirm_sign_out': 'Confirm Sign Out',
      'confirm_transaction': 'Confirm Transaction',
      'copy_reminder_template': 'Copy Reminder Template',
      'create_subscription': 'Create Subscription',
      'credit_cards': 'Credit Cards',
      'deduct_from_account': 'Deduct From Account',
      'delete': 'Delete',
      'delete_card': 'Delete Card',
      'delete_category': 'Delete Category?',
      'delete_subscription': 'Delete Subscription?',
      'divide_into_installments': 'Divide into Installments',
      'due_in': 'Due in',
      'edit_account_info': 'Edit Account Info',
      'edit_card': 'Edit Card',
      'edit_person_name': 'Edit Person Name',
      'enter_your_4digit_security': 'Enter your 4-digit security PIN',
      'expense': 'Expense',
      'frequency': 'FREQUENCY',
      'full_balance': 'FULL BALANCE',
      'filter_transactions': 'Filter Transactions',
      'for_security_do_not': 'For security, do not enter PINs, CVVs, or passwords.',
      'forgot_security_pin': 'Forgot Security PIN?',
      'frequency_1': 'Frequency',
      'given_by': 'GIVEN BY',
      'initial_progress_already_done': 'INITIAL PROGRESS (ALREADY DONE)',
      'installment_timeline': 'INSTALLMENT TIMELINE',
      'installments': 'INSTALLMENTS',
      'income': 'Income',
      'load_more': 'Load More',
      'loan_details': 'Loan Details',
      'loans': 'Loans',
      'member_breakdown': 'MEMBER BREAKDOWN',
      'mobile_wallet_details': 'MOBILE WALLET DETAILS',
      'monthly_analytics': 'Monthly Analytics',
      'monthly_budget_health': 'Monthly Budget Health',
      'monthly_estimated_dues': 'Monthly Estimated Dues',
      'monthly_goals': 'Monthly Goals',
      'monthly_sheet_copied_to': 'Monthly sheet copied to clipboard as CSV!',
      'my_savings': 'My Savings',
      'new_account': 'New Account',
      'new_loan': 'New Loan',
      'new_subscription': 'New Subscription',
      'next_due_date': 'Next Due Date',
      'next_statement': 'Next Statement',
      'no_credit_cards_yet': 'No Credit Cards yet',
      'no_subscriptions_yet': 'No Subscriptions Yet',
      'no_transactions_found': 'No Transactions Found',
      'no_categories_found': 'No categories found',
      'no_loans_found': 'No loans found',
      'no_recent_transactions': 'No recent transactions',
      'no_repayments_yet': 'No repayments yet.',
      'no_transactions_recorded_yet': 'No transactions recorded yet',
      'no_transactions_to_export': 'No transactions to export for this month',
      'no_vaults_found_tap': 'No vaults found. Tap Add Account to create your first savings vault.',
      'none_outside_app': 'None (Outside App)',
      'note_optional': 'Note (Optional)',
      'note_optional_1': 'Note (optional)',
      'notifications': 'Notifications',
      'owner_share_distribution': 'OWNER SHARE DISTRIBUTION',
      'owner_split': 'OWNER SPLIT',
      'outstanding': 'Outstanding',
      'pay_log': 'Pay & Log',
      'pay_bill': 'Pay Bill',
      'payment_due': 'Payment Due',
      'payment_recieved': 'Payment Recieved',
      'payment_cannot_exceed_remaining': 'Payment cannot exceed remaining balance',
      'person_name_eg_rahim': 'Person Name (e.g. Rahim)',
      'please_enter_account_name': 'Please enter account name',
      'please_enter_amount': 'Please enter amount',
      'please_enter_an_amount': 'Please enter an amount',
      'please_enter_name_and': 'Please enter name and amount',
      'please_select_destination_account': 'Please select destination account',
      'please_select_payment_source': 'Please select payment source',
      'repayment_reminder_template': 'REPAYMENT REMINDER TEMPLATE',
      'reminder_template_copied': 'Reminder template copied!',
      'repayment_history': 'Repayment History',
      'routing_number': 'Routing Number',
      'save': 'Save',
      'save_card': 'Save Card',
      'save_changes': 'Save Changes',
      'save_loan': 'Save Loan',
      'save_transaction': 'Save Transaction',
      'savings_dashboard': 'Savings Dashboard',
      'search_by_note_category': 'Search by note, category, or amount...',
      'search_by_person_name': 'Search by person name or note...',
      'secure_savings_vault': 'Secure Savings Vault',
      'see_all': 'See all',
      'select_account': 'Select Account',
      'select_account_optional': 'Select Account (Optional)',
      'select_color': 'Select Color',
      'select_icon': 'Select Icon',
      'select_month_year': 'Select Month & Year',
      'set_monthly_targets': 'Set Monthly Targets',
      'set_income_targets_and': 'Set income targets and expense limits to get a detailed breakdown of your savings potential and financial health.',
      'seyam_ali': 'Seyam Ali',
      'split_this_loan_into': 'Split this loan into smaller payments',
      'subscriptions_bills': 'Subscriptions & Bills',
      'total_assets': 'TOTAL ASSETS',
      'total_balance': 'TOTAL BALANCE',
      'total_expense': 'TOTAL EXPENSE',
      'total_income': 'TOTAL INCOME',
      'transaction_history': 'TRANSACTION HISTORY',
      'tap_the_add_button': 'Tap the add button to insert a transaction',
      'target_settings': 'Target Settings',
      'to_protect_your_personal': 'To protect your personal ledger, you must sign out of your account and log back in with your password to disable or reset your PIN code.',
      'total_balance_1': 'Total Balance',
      'total_net_savings': 'Total Net Savings',
      'track_your_income_expense': 'Track your income & expense targets',
      'transactions': 'Transactions',
      'trends_summary': 'Trends Summary',
      'update_targets': 'Update Targets',
      'wallet_mobile_number': 'Wallet Mobile Number',
      'where_is_my_money': 'Where is my money?',
      'your_savings_vaults': 'YOUR SAVINGS VAULTS',
      'you_have_no_pending': 'You have no pending alerts or upcoming payments.',
      'eg_dbbl_bkash_my': 'e.g. DBBL, bKash, My Wallet',
      'track_money_stay_in': '— Track Money. Stay in Control. —',
      'combined_balance_of_all': '“Combined balance of all MFS, Bank & Cash accounts”',
    
      // Dashboard
      'recent_transactions': 'Recent Transactions',
      'goals': 'Goals',
      'advisor_update': 'Advisor Update',
      'loan_taken': 'Loan Taken',
      'bills': 'Bills',
      'me': 'Me',
      'quick_actions': 'Quick Actions',
      'savings_and_loans': 'Savings & Loans',
      'taken': 'Taken',
      'budget_warning': 'Budget Warning!',
      'upcoming_bill_due': 'Upcoming Bill Due',
      'set_goal': 'Set Goal',
      'adjust_goals': 'Adjust Goals',
      'set_your_goals': 'Set Your Goals',
      'records': 'Records',
      'overdue_bills_alert': 'Overdue Bills Alert',
      'view_trends': 'View Trends',
      'good_morning': 'Good Morning',
      'bill_due_today': 'Bill Due Today',
      'savings_alert': 'Savings Alert',
      'view_analytics': 'View Analytics',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'received': 'Received',
      'smart': 'Smart',
      'category_spike': 'Category Spike!',
      'excellent_cashflow': 'Excellent Cashflow!',
      'track_your_income_and_expense_targets': 'Track your income & expense targets',
      'budget_exceeded': 'Budget Exceeded!',
      'log_savings': 'Log Savings',
      'loan_given': 'Loan Given',
      'credit': 'Credit',
      'savings': 'Savings',
},
    'bn': {
      // Login Screen
      'welcome_back': 'পুনরায় স্বাগতম!',
      'login_subtitle': 'আপনার আর্থিক লেনদেন পরিচালনা করতে সাইন ইন করুন',
      'email': 'ইমেইল',
      'email_hint': 'আপনার ইমেইল লিখুন',
      'password': 'পাসওয়ার্ড',
      'password_hint': 'আপনার পাসওয়ার্ড লিখুন',
      'sign_in': 'লগ ইন করুন',
      'no_account': 'নতুন ব্যবহারকারী? ',
      'sign_up_now': 'অ্যাকাউন্ট তৈরি করুন',
      'email_required': 'ইমেইল ঠিকানা আবশ্যক',
      'password_required': 'পাসওয়ার্ড আবশ্যক',
      'invalid_credentials': 'ভুল ইমেইল বা পাসওয়ার্ড প্রদান করা হয়েছে',
      'login_failed': 'লগ ইন ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।',

      // Signup Screen
      'create_account': 'অ্যাকাউন্ট তৈরি করুন',
      'signup_subtitle': 'আর্থিক স্বাধীনতার পথে আপনার যাত্রা শুরু করুন',
      'full_name': 'সম্পূর্ণ নাম',
      'confirm_password': 'পাসওয়ার্ড নিশ্চিত করুন',
      'already_have_account': 'ইতিমধ্যেই একটি অ্যাকাউন্ট আছে? ',
      
      // Nav Bar
      'home': 'হোম',
      'wallet': 'ওয়ালেট',
      'stats': 'পরিসংখ্যান',

      // Profile Screen
      'profile': 'প্রোফাইল',
      'edit_profile': 'প্রোফাইল সম্পাদনা',
      'account_settings': 'অ্যাকাউন্ট সেটিংস',
      'language': 'ভাষা (Language)',
      'dark_mode': 'ডার্ক মোড',
      'biometric_lock': 'বায়োমেট্রিক লক',
      'help_support': 'সাহায্য ও সাপোর্ট',
      'about_app': 'অ্যাপ সম্পর্কে',
      'log_out': 'লগ আউট',
      'confirm_logout': 'লগ আউট নিশ্চিত করুন',
      'logout_message': 'আপনি কি নিশ্চিত যে আপনি লগ আউট করতে চান?',
      'cancel': 'বাতিল',
      'user_details_error': 'ব্যবহারকারীর তথ্য লোড করা যায়নি',
      'account_information': 'অ্যাকাউন্ট তথ্য',
      'account_name': 'অ্যাকাউন্টের নাম',
      'active_timelines': 'সক্রিয় সময়সীমা',
      'ai_wealth_copilot': 'এআই ওয়েলথ কো-পাইলট',
      'amount': 'পরিমাণ',
      'account_name_1': 'অ্যাকাউন্টের নাম',
      'account_number': 'অ্যাকাউন্ট নম্বর',
      'accountwise_distribution': 'অ্যাকাউন্ট অনুযায়ী বন্টন',
      'accounts': 'অ্যাকাউন্টসমূহ',
      'add_card': 'কার্ড যোগ করুন',
      'add_a_credit_card': 'আপনার ব্যালেন্স এবং বিল ট্র্যাক করতে একটি ক্রেডিট কার্ড যোগ করুন।',
      'add_a_note': 'একটি নোট যোগ করুন...',
      'add_a_savings_account': 'প্রথমে একটি সেভিংস অ্যাকাউন্ট যোগ করুন!',
      'add_amounts_done_before': 'এই মাসে অ্যাপ ব্যবহারের আগের পরিমাণ যোগ করুন',
      'add_an_account_to': 'আপনার সম্পদ দেখতে একটি অ্যাকাউন্ট যোগ করুন',
      'add_your_recurring_bills': 'আপনার নিয়মিত বিল বা সাবস্ক্রিপশন যোগ করুন এবং আর কখনো নির্ধারিত তারিখ মিস করবেন না।',
      'adjust_account_balance': 'অ্যাকাউন্টের ব্যালেন্স সমন্বয় করুন',
      'all_caught_up': 'সব ঠিক আছে!',
      'all_scheduled_subscriptions_and': 'সব নির্ধারিত সাবস্ক্রিপশন এবং নিয়মিত পেমেন্ট',
      'already_paiddeducted': 'ইতোমধ্যে পরিশোধিত/কাটা হয়েছে?',
      'app_locked': 'অ্যাপ লক করা আছে',
      'apply': 'প্রয়োগ করুন',
      'are_you_sure_you': 'আপনি কি নিশ্চিত যে এই ক্রেডিট কার্ড মুছে ফেলতে চান? এটি আর ফেরানো যাবে না।',
      'are_you_sure_you_1': 'আপনি কি নিশ্চিত যে এই বিল মুছে ফেলতে চান? আগের পেমেন্ট রেকর্ডগুলো থেকে যাবে।',
      'available_credit': 'উপলব্ধ ক্রেডিট',
      'available_limit': 'উপলব্ধ সীমা',
      'bank_account_details': 'ব্যাংক অ্যাকাউন্টের বিবরণ',
      'branch_name': 'শাখার নাম',
      'card_payment': 'কার্ড পেমেন্ট',
      'combined_portfolio_balance': 'সম্মিলিত পোর্টফোলিও ব্যালেন্স',
      'copy_all': 'সব কপি করুন',
      'card_color_theme': 'কার্ডের রঙের থিম',
      'card_details': 'কার্ডের বিবরণ',
      'card_network': 'কার্ড নেটওয়ার্ক',
      'card_number_eg_last': 'কার্ড নম্বর (উদাঃ শেষ ৪ সংখ্যা)',
      'card_number_last_4': 'কার্ড নম্বর (শেষ ৪ সংখ্যা বা সম্পূর্ণ)',
      'card_not_found': 'কার্ড পাওয়া যায়নি',
      'category': 'ক্যাটাগরি',
      'category_manager': 'ক্যাটাগরি ম্যানেজার',
      'category_type': 'ক্যাটাগরির ধরন',
      'change': 'পরিবর্তন',
      'choose_how_you_want': 'আপনি কীভাবে তারিখ ফিল্টার করতে চান তা নির্বাচন করুন',
      'confirm': 'নিশ্চিত করুন',
      'confirm_sign_out': 'সাইন আউট নিশ্চিত করুন',
      'confirm_transaction': 'লেনদেন নিশ্চিত করুন',
      'copy_reminder_template': 'রিমাইন্ডার টেমপ্লেট কপি করুন',
      'create_subscription': 'সাবস্ক্রিপশন তৈরি করুন',
      'credit_cards': 'ক্রেডিট কার্ডসমূহ',
      'deduct_from_account': 'অ্যাকাউন্ট থেকে কাটুন',
      'delete': 'মুছে ফেলুন',
      'delete_card': 'কার্ড মুছে ফেলুন',
      'delete_category': 'ক্যাটাগরি মুছে ফেলবেন?',
      'delete_subscription': 'সাবস্ক্রিপশন মুছে ফেলবেন?',
      'divide_into_installments': 'কিস্তিতে ভাগ করুন',
      'due_in': 'বাকি আছে',
      'edit_account_info': 'অ্যাকাউন্টের তথ্য সম্পাদনা করুন',
      'edit_card': 'কার্ড সম্পাদনা করুন',
      'edit_person_name': 'ব্যক্তির নাম সম্পাদনা করুন',
      'enter_your_4digit_security': 'আপনার ৪-সংখ্যার সিকিউরিটি পিন দিন',
      'expense': 'খরচ',
      'frequency': 'ফ্রিকোয়েন্সি',
      'full_balance': 'পূর্ণ ব্যালেন্স',
      'filter_transactions': 'লেনদেন ফিল্টার করুন',
      'for_security_do_not': 'নিরাপত্তার স্বার্থে পিন, সিভিভি বা পাসওয়ার্ড দিবেন না।',
      'forgot_security_pin': 'সিকিউরিটি পিন ভুলে গেছেন?',
      'frequency_1': 'ফ্রিকোয়েন্সি',
      'given_by': 'প্রদান করেছেন',
      'initial_progress_already_done': 'প্রাথমিক অগ্রগতি (ইতোমধ্যে সম্পন্ন)',
      'installment_timeline': 'কিস্তির সময়সীমা',
      'installments': 'কিস্তিসমূহ',
      'income': 'আয়',
      'load_more': 'আরও লোড করুন',
      'loan_details': 'ঋণের বিস্তারিত বিবরণ',
      'loans': 'ঋণসমূহ',
      'member_breakdown': 'সদস্যভিত্তিক বিশ্লেষণ',
      'mobile_wallet_details': 'মোবাইল ওয়ালেটের বিস্তারিত বিবরণ',
      'monthly_analytics': 'মাসিক বিশ্লেষণ',
      'monthly_budget_health': 'মাসিক বাজেটের অবস্থা',
      'monthly_estimated_dues': 'মাসিক সম্ভাব্য বকেয়া',
      'monthly_goals': 'মাসিক লক্ষ্য',
      'monthly_sheet_copied_to': 'মাসিক শিট সিএসভি হিসেবে ক্লিপবোর্ডে কপি করা হয়েছে!',
      'my_savings': 'আমার সঞ্চয়',
      'new_account': 'নতুন অ্যাকাউন্ট',
      'new_loan': 'নতুন ঋণ',
      'new_subscription': 'নতুন সাবস্ক্রিপশন',
      'next_due_date': 'পরবর্তী নির্ধারিত তারিখ',
      'next_statement': 'পরবর্তী স্টেটমেন্ট',
      'no_credit_cards_yet': 'কোনো ক্রেডিট কার্ড নেই',
      'no_subscriptions_yet': 'কোনো সাবস্ক্রিপশন নেই',
      'no_transactions_found': 'কোনো লেনদেন পাওয়া যায়নি',
      'no_categories_found': 'কোনো ক্যাটাগরি পাওয়া যায়নি',
      'no_loans_found': 'কোনো ঋণ পাওয়া যায়নি',
      'no_recent_transactions': 'কোনো সাম্প্রতিক লেনদেন নেই',
      'no_repayments_yet': 'কোনো পরিশোধ করা হয়নি।',
      'no_transactions_recorded_yet': 'এখনও কোনো লেনদেন রেকর্ড করা হয়নি',
      'no_transactions_to_export': 'এই মাসের জন্য এক্সপোর্ট করার মতো কোনো লেনদেন নেই',
      'no_vaults_found_tap': 'কোনো ভল্ট পাওয়া যায়নি। অ্যাকাউন্ট যোগ করতে আলতো চাপুন।',
      'none_outside_app': 'কিছুই না (অ্যাপের বাইরে)',
      'note_optional': 'নোট (ঐচ্ছিক)',
      'note_optional_1': 'নোট (ঐচ্ছিক)',
      'notifications': 'নোটিফিকেশন',
      'owner_share_distribution': 'মালিকানার শেয়ার বন্টন',
      'owner_split': 'মালিকানা বিভাজন',
      'outstanding': 'বকেয়া',
      'pay_log': 'পে এবং লগ',
      'pay_bill': 'বিল পে',
      'payment_due': 'পেমেন্ট বাকি',
      'payment_recieved': 'পেমেন্ট গ্রহণ করা হয়েছে',
      'payment_cannot_exceed_remaining': 'পেমেন্ট বাকি পরিমাণের চেয়ে বেশি হতে পারে না',
      'person_name_eg_rahim': 'ব্যক্তির নাম (উদাঃ রহিম)',
      'please_enter_account_name': 'অনুগ্রহ করে অ্যাকাউন্টের নাম লিখুন',
      'please_enter_amount': 'অনুগ্রহ করে পরিমাণ দিন',
      'please_enter_an_amount': 'অনুগ্রহ করে একটি পরিমাণ দিন',
      'please_enter_name_and': 'অনুগ্রহ করে নাম এবং পরিমাণ দিন',
      'please_select_destination_account': 'অনুগ্রহ করে গন্তব্য অ্যাকাউন্ট নির্বাচন করুন',
      'please_select_payment_source': 'অনুগ্রহ করে পেমেন্ট সোর্স নির্বাচন করুন',
      'repayment_reminder_template': 'পরিশোধের রিমাইন্ডার টেমপ্লেট',
      'reminder_template_copied': 'রিমাইন্ডার টেমপ্লেট কপি করা হয়েছে!',
      'repayment_history': 'পরিশোধের ইতিহাস',
      'routing_number': 'রাউটিং নম্বর',
      'save': 'সংরক্ষণ করুন',
      'save_card': 'কার্ড সংরক্ষণ করুন',
      'save_changes': 'পরিবর্তনগুলো সংরক্ষণ করুন',
      'save_loan': 'ঋণ সংরক্ষণ করুন',
      'save_transaction': 'লেনদেন সংরক্ষণ করুন',
      'savings_dashboard': 'সঞ্চয় ড্যাশবোর্ড',
      'search_by_note_category': 'নোট, ক্যাটাগরি, বা পরিমাণ দিয়ে খুঁজুন...',
      'search_by_person_name': 'ব্যক্তির নাম বা নোট দিয়ে খুঁজুন...',
      'secure_savings_vault': 'নিরাপদ সঞ্চয় ভল্ট',
      'see_all': 'সবগুলো দেখুন',
      'select_account': 'অ্যাকাউন্ট নির্বাচন করুন',
      'select_account_optional': 'অ্যাকাউন্ট নির্বাচন করুন (ঐচ্ছিক)',
      'select_color': 'রঙ নির্বাচন করুন',
      'select_icon': 'আইকন নির্বাচন করুন',
      'select_month_year': 'মাস এবং বছর নির্বাচন করুন',
      'set_monthly_targets': 'মাসিক লক্ষ্য নির্ধারণ করুন',
      'set_income_targets_and': 'আপনার আর্থিক স্বাস্থ্যের সঠিক বিশ্লেষণ পেতে লক্ষ্য নির্ধারণ করুন।',
      'seyam_ali': 'সিয়াম আলী',
      'split_this_loan_into': 'এই ঋণটি ছোট ছোট পেমেন্টে ভাগ করুন',
      'subscriptions_bills': 'সাবস্ক্রিপশন এবং বিল',
      'total_assets': 'মোট সম্পদ',
      'total_balance': 'মোট ব্যালেন্স',
      'total_expense': 'মোট খরচ',
      'total_income': 'মোট আয়',
      'transaction_history': 'লেনদেনের ইতিহাস',
      'tap_the_add_button': 'একটি লেনদেন সন্নিবেশ করতে যোগ করুন বোতামে চাপুন',
      'target_settings': 'লক্ষ্য সেটিংস',
      'to_protect_your_personal': 'আপনার ব্যক্তিগত হিসাব সুরক্ষিত রাখতে, পিন রিসেট করার জন্য সাইন আউট করে পুনরায় লগ ইন করুন।',
      'total_balance_1': 'মোট ব্যালেন্স',
      'total_net_savings': 'মোট নিট সঞ্চয়',
      'track_your_income_expense': 'আপনার আয় ও খরচের লক্ষ্য ট্র্যাক করুন',
      'transactions': 'লেনদেনসমূহ',
      'trends_summary': 'ট্রেন্ডের সারাংশ',
      'update_targets': 'লক্ষ্য আপডেট করুন',
      'wallet_mobile_number': 'ওয়ালেটের মোবাইল নম্বর',
      'where_is_my_money': 'আমার টাকা কোথায়?',
      'your_savings_vaults': 'আপনার সঞ্চয় ভল্টসমূহ',
      'you_have_no_pending': 'আপনার কোনো বকেয়া অ্যালার্ট নেই।',
      'eg_dbbl_bkash_my': 'উদাঃ ডিবিবিএল, বিকাশ, মাই ওয়ালেট',
      'track_money_stay_in': '— টাকা ট্র্যাক করুন। নিয়ন্ত্রণে থাকুন। —',
      'combined_balance_of_all': '“সকল এমএফএস, ব্যাংক এবং নগদ অ্যাকাউন্টের সম্মিলিত ব্যালেন্স”',
    
      // Dashboard
      'recent_transactions': 'সাম্প্রতিক লেনদেন',
      'goals': 'লক্ষ্যসমূহ',
      'advisor_update': 'উপদেষ্টা আপডেট',
      'loan_taken': 'গৃহীত ঋণ',
      'bills': 'বিলসমূহ',
      'me': 'আমার',
      'quick_actions': 'দ্রুত কাজ',
      'savings_and_loans': 'সঞ্চয় ও ঋণ',
      'taken': 'গৃহীত',
      'budget_warning': 'বাজেট সতর্কতা!',
      'upcoming_bill_due': 'আসন্ন বিল',
      'set_goal': 'লক্ষ্য নির্ধারণ করুন',
      'adjust_goals': 'লক্ষ্য সামঞ্জস্য করুন',
      'set_your_goals': 'আপনার লক্ষ্য নির্ধারণ করুন',
      'records': 'রেকর্ড',
      'overdue_bills_alert': 'বকেয়া বিল সতর্কতা',
      'view_trends': 'ট্রেন্ড দেখুন',
      'good_morning': 'শুভ সকাল',
      'bill_due_today': 'আজকের বিল',
      'savings_alert': 'সঞ্চয় সতর্কতা',
      'view_analytics': 'বিশ্লেষণ দেখুন',
      'good_afternoon': 'শুভ অপরাহ্ন',
      'good_evening': 'শুভ সন্ধ্যা',
      'received': 'গৃহীত',
      'smart': 'স্মার্ট',
      'category_spike': 'বিভাগ বৃদ্ধি!',
      'excellent_cashflow': 'চমৎকার ক্যাশফ্লো!',
      'track_your_income_and_expense_targets': 'আপনার আয় ও ব্যয়ের লক্ষ্য ট্র্যাক করুন',
      'budget_exceeded': 'বাজেট অতিক্রম করেছে!',
      'log_savings': 'সঞ্চয় লগ করুন',
      'loan_given': 'প্রদত্ত ঋণ',
      'credit': 'ক্রেডিট',
      'savings': 'সঞ্চয়',
}
  };

  static String get(String key) {
    final String langCode = LanguageService().currentLanguage;
    return _localizedValues[langCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}
