import 'package:pocketledger/services/language_service.dart';

class AppLocalizations {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Login Screen
      'welcome_back': 'Welcome Back!',
      'login_subtitle': 'Sign in to manage your finances',
      'email': 'Email',
      'email_hint': 'Enter your email',
      'password': 'Password',
      'password_hint': 'Enter your password',
      'sign_in': 'Sign In',
      'no_account': "Don't have an account? ",
      'sign_up_now': 'Sign Up Now',
      'email_required': 'Email is required',
      'password_required': 'Password is required',
      'invalid_credentials': 'Invalid email or password',
      'login_failed': 'Failed to sign in. Please try again.',
      
      // Signup Screen
      'create_account': 'Create Account',
      'signup_subtitle': 'Start your journey to financial freedom',
      'full_name': 'Full Name',
      'confirm_password': 'Confirm Password',
      'already_have_account': 'Already have an account? ',

      // Nav Bar
      'home': 'Home',
      'wallet': 'Wallet',
      'stats': 'Stats',

      // Profile Screen
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'account_settings': 'Account Settings',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'biometric_lock': 'Biometric Lock',
      'help_support': 'Help & Support',
      'about_app': 'About App',
      'log_out': 'Log Out',
      'confirm_logout': 'Confirm Logout',
      'logout_message': 'Are you sure you want to log out?',
      'cancel': 'Cancel',
      'user_details_error': 'Could not load user details',
      'account_information': 'ACCOUNT INFORMATION',
      'account_name': 'ACCOUNT NAME',
      'active_timelines': 'ACTIVE TIMELINES',
      'ai_wealth_copilot': 'AI WEALTH COPILOT',
      'amount': 'AMOUNT',
      'amount_to_save': 'Amount to Save',
      'account_name_1': 'Account Name',
      'account_number': 'Account Number',
      'account_name_eg_savings': 'Account Name (e.g. DPS, bKash)',
      'add_money': 'Add Money',
      'accountwise_distribution': 'Account-wise distribution',
      'accounts': 'Accounts',
      'add_account': 'Add Account',
      'add_card': 'Add Card',
      'add_a_credit_card': 'Add a credit card to track your balances, bills, and due dates.',
      'add_a_note': 'Add a note...',
      'add_a_savings_account': 'Add a savings account first!',
      'add_amounts_done_before': 'Add amounts done before using this app this month',
      'add_an_account_to': 'Add an account to see your assets here',
      'add_your_recurring_bills': 'Add your recurring bills, subscriptions, or utility payments and never miss a due date again.',
      'add_to_savings': 'Add to Savings',
      'adjust_account_balance': 'Adjust Account Balance',
      'all': 'All',
      'all_caught_up': 'All caught up!',
      'all_scheduled_subscriptions_and': 'All scheduled subscriptions and recurring logs combined',
      'already_paiddeducted': 'Already paid/deducted?',
      'app_locked': 'App Locked',
      'apply': 'Apply',
      'are_you_sure_you': 'Are you sure you want to delete this credit card? This action cannot be undone.',
      'are_you_sure_you_1': 'Are you sure you want to delete this recurring bill? Historical payments logged will not be deleted.',
      'available_credit': 'Available Credit',
      'available_limit': 'Available Limit',
      'all_bank_details': 'All bank details',
      'all_time': 'All Time',
      'bank': 'Bank',
      'bank_account_details': 'BANK ACCOUNT DETAILS',
      'branch_name': 'Branch Name',
      'card_payment': 'CARD PAYMENT',
      'combined_portfolio_balance': 'COMBINED PORTFOLIO BALANCE',
      'copy_all': 'COPY ALL',
      'copied_to_clipboard': '{label} copied to clipboard!',
      'card_color_theme': 'Card Color Theme',
      'card_details': 'Card Details',
      'card_network': 'Card Network',
      'card_number': 'Card Number',
      'card_number_eg_last': 'Card Number (e.g. last 4 digits)',
      'card_number_last_4': 'Card Number (last 4 digits or full)',
      'card_not_found': 'Card not found',
      'category': 'Category',
      'category_subtitle': 'What kind of transaction?',
      'category_manager': 'Category Manager',
      'category_type': 'Category Type',
      'change': 'Change',
      'choose_how_you_want': 'Choose how you want to filter dates',
      'confirm': 'Confirm',
      'confirm_sign_out': 'Confirm Sign Out',
      'confirm_transaction': 'Confirm Transaction',
      'copy_reminder_template': 'Copy Reminder Template',
      'create_subscription': 'Create Subscription',
      'credit_cards': 'Credit Cards',
      'credit_card_payment': 'Credit Card Payment',
      'deduct_from_account': 'Deduct From Account',
      'deduct_from': 'Deduct From',
      'delete': 'Delete',
      'delete_card': 'Delete Card',
      'delete_category': 'Delete Category?',
      'delete_subscription': 'Delete Subscription?',
      'destination': 'Destination',
      'destination_card': 'Destination card',
      'destination_member': 'Destination Member',
      'destination_subtitle': 'Where is it going?',
      'divide_into_installments': 'Divide into Installments',
      'due_in': 'Due in',
      'edit_account_info': 'Edit Account Info',
      'edit_card': 'Edit Card',
      'edit_person_name': 'Edit Person Name',
      'error': 'Error',
      'error_loading_transactions': 'Error loading transactions',
      'enter_your_4digit_security': 'Enter your 4-digit security PIN',
      'expense': 'Expense',
      'frequency': 'FREQUENCY',
      'full_balance': 'FULL BALANCE',
      'filter_transactions': 'Filter Transactions',
      'for_security_do_not': 'For security, do not enter PINs, CVVs, or passwords.',
      'forgot_security_pin': 'Forgot Security PIN?',
      'frequency_1': 'Frequency',
      'given_by': 'GIVEN BY',
      'initial_progress_already_done': 'INITIAL PROGRESS (ALREADY DONE)',
      'installment_timeline': 'INSTALLMENT TIMELINE',
      'installments': 'INSTALLMENTS',
      'income': 'Income',
      'load_more': 'Load More',
      'loan_details': 'Loan Details',
      'loans': 'Loans',
      'member_breakdown': 'MEMBER BREAKDOWN',
      'mobile_wallet_details': 'MOBILE WALLET DETAILS',
      'mobile_number': 'Mobile Number',
      'monthly_analytics': 'Monthly Analytics',
      'monthly_budget_health': 'Monthly Budget Health',
      'monthly_estimated_dues': 'Monthly Estimated Dues',
      'monthly_goals': 'Monthly Goals',
      'monthly_sheet_copied_to': 'Monthly sheet copied to clipboard as CSV!',
      'month_short_1': 'Jan',
      'month_short_2': 'Feb',
      'month_short_3': 'Mar',
      'month_short_4': 'Apr',
      'month_short_5': 'May',
      'month_short_6': 'Jun',
      'month_short_7': 'Jul',
      'month_short_8': 'Aug',
      'month_short_9': 'Sep',
      'month_short_10': 'Oct',
      'month_short_11': 'Nov',
      'month_short_12': 'Dec',
      'my_savings': 'My Savings',
      'new_account': 'New Account',
      'new_loan': 'New Loan',
      'new_savings_account': 'New Savings Account',
      'new_subscription': 'New Subscription',
      'next_due_date': 'Next Due Date',
      'next_statement': 'Next Statement',
      'no_credit_cards_yet': 'No Credit Cards yet',
      'no_subscriptions_yet': 'No Subscriptions Yet',
      'no_transactions_found': 'No Transactions Found',
      'no_categories_found': 'No categories found',
      'no_loans_found': 'No loans found',
      'no_recent_transactions': 'No recent transactions',
      'no_repayments_yet': 'No repayments yet.',
      'no_transactions_recorded_yet': 'No transactions recorded yet',
      'no_transactions_to_export': 'No transactions to export for this month',
      'no_vaults_found_tap': 'No vaults found. Tap Add Account to create your first savings vault.',
      'none_outside_app': 'None (Outside App)',
      'note_optional': 'Note (Optional)',
      'note_optional_1': 'Note (optional)',
      'notifications': 'Notifications',
      'note': 'Note',
      'notes': 'Notes',
      'notes_subtitle': 'Add extra details',
      'owner_share_distribution': 'OWNER SHARE DISTRIBUTION',
      'owner_split': 'OWNER SPLIT',
      'outstanding': 'Outstanding',
      'opening_balance': 'Opening Balance',
      'others': 'Others',
      'pay_log': 'Pay & Log',
      'pay_bill': 'Pay Bill',
      'payment_due': 'Payment Due',
      'payment_recieved': 'Payment Recieved',
      'payment_cannot_exceed_remaining': 'Payment cannot exceed remaining balance',
      'paying_bill_for': 'Paying Bill For',
      'person_name_eg_rahim': 'Person Name (e.g. Rahim)',
      'please_enter_account_name': 'Please enter account name',
      'please_enter_amount': 'Please enter amount',
      'please_enter_an_amount': 'Please enter an amount',
      'please_enter_name_and': 'Please enter name and amount',
      'please_select_destination_account': 'Please select destination account',
      'please_select_payment_source': 'Please select payment source',
      'repayment_reminder_template': 'REPAYMENT REMINDER TEMPLATE',
      'reminder_template_copied': 'Reminder template copied!',
      'repayment_history': 'Repayment History',
      'routing_number': 'Routing Number',
      'save': 'Save',
      'save_card': 'Save Card',
      'save_changes': 'Save Changes',
      'save_into': 'Save Into',
      'save_loan': 'Save Loan',
      'save_transaction': 'Save Transaction',
      'savings_dashboard': 'Savings Dashboard',
      'search_by_note_category': 'Search by note, category, or amount...',
      'search_by_person_name': 'Search by person name or note...',
      'secure_savings_vault': 'Secure Savings Vault',
      'see_all': 'See all',
      'select_account': 'Select Account',
      'select_account_optional': 'Select Account (Optional)',
      'select_color': 'Select Color',
      'select_custom_date_range': 'Select Custom Date Range',
      'select_custom_date_range_subtitle': 'Choose a specific start date and end date',
      'select_icon': 'Select Icon',
      'select_month_year': 'Select Month & Year',
      'select_specific_month_year': 'Select Specific Month & Year',
      'select_specific_month_year_subtitle': 'Filter by any specific month (e.g. March 2026)',
      'set_monthly_targets': 'Set Monthly Targets',
      'set_income_targets_and': 'Set income targets and expense limits to get a detailed breakdown of your savings potential and financial health.',
      'seyam_ali': 'Seyam Ali',
      'self': 'Self',
      'show_all_time': 'Show All Time',
      'show_all_time_subtitle': 'Remove date filters and show all transactions',
      'source': 'Source',
      'source_member': 'Source Member',
      'source_subtitle': 'Where is this from?',
      'split_this_loan_into': 'Split this loan into smaller payments',
      'subscriptions_bills': 'Subscriptions & Bills',
      'total_assets': 'TOTAL ASSETS',
      'total_balance': 'TOTAL BALANCE',
      'total_expense': 'TOTAL EXPENSE',
      'total_income': 'TOTAL INCOME',
      'transaction_history': 'TRANSACTION HISTORY',
      'tap_the_add_button': 'Tap the add button to insert a transaction',
      'target_settings': 'Target Settings',
      'this_month': 'This Month',
      'this_month_subtitle': 'Show transactions from the current month',
      'this_week': 'This Week',
      'this_week_subtitle': 'Show transactions from the last 7 days',
      'to_protect_your_personal': 'To protect your personal ledger, you must sign out of your account and log back in with your password to disable or reset your PIN code.',
      'to_owner': 'To Owner',
      'total_balance_1': 'Total Balance',
      'total_net_savings': 'Total Net Savings',
      'track_your_income_expense': 'Track your income & expense targets',
      'transactions': 'Transactions',
      'transfer': 'Transfer',
      'trends_summary': 'Trends Summary',
      'tx_type': 'Tx Type',
      'update_targets': 'Update Targets',
      'wallet_mobile_number': 'Wallet Mobile Number',
      'wallet_details': 'Wallet details',
      'wallet_name': 'Wallet Name',
      'where_is_my_money': 'Where is my money?',
      'who_is_receiving': 'Who is receiving?',
      'who_is_sending': 'Who is sending?',
      'withdraw': 'Withdraw',
      'wont_cut_balance': "Won't cut from your wallet/cash balance",
      'complete_saving': 'Complete Saving',
      'your_savings_vaults': 'YOUR SAVINGS VAULTS',
      'you_have_no_pending': 'You have no pending alerts or upcoming payments.',
      'eg_dbbl_bkash_my': 'e.g. DBBL, bKash, My Wallet',
      'track_money_stay_in': '— Track Money. Stay in Control. —',
      'combined_balance_of_all': '“Combined balance of all MFS, Bank & Cash accounts”',
      'given_total': 'GIVEN TOTAL',
      'taken_total': 'TAKEN TOTAL',
      'pending': 'PENDING',
      'given': 'Given',
      'by_person': 'By Person',
      'settled': 'SETTLED',
      'they_owe': 'THEY OWE',
      'you_owe': 'YOU OWE',
      'given_pending': 'Given (Pending)',
      'taken_pending': 'Taken (Pending)',
      'net_balance': 'Net Balance',
      'loan_count_one': '{count} loan',
      'loan_count_many': '{count} loans',
      'paid': 'PAID',
      'total_given': 'Total Given',
      'total_taken': 'Total Taken',
      'paid_back': 'Paid Back',
      'remaining': 'Remaining',
      'person_name': 'PERSON NAME',
      'loan_owner_portion': 'LOAN OWNER / PORTION',
      'link_account_optional': 'LINK ACCOUNT (OPTIONAL)',
      'given_loan': 'Given Loan',
      'taken_loan': 'Taken Loan',
      'balance_update_on': 'ON - Balance will be updated now',
      'balance_update_off': 'OFF - Only records the loan (balance already correct)',
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'installment_times': '{count} times',
      'installment_summary': 'Splits this loan into {count} installments of ৳{amount} paid {frequency}.',
      'receive_from': 'Receive from {name}',
      'repay_to': 'Repay to {name}',
      'money_added_to_account': 'Money will be added to your account',
      'record_money_movement': 'Record where the money is moving',
      'amount_max': 'Amount (Max: {amount})',
      'repay_from_my_pocket': 'REPAY FROM (MY POCKET)',
      'add_to_my_app_account': 'Add to my App Account?',
      'return_to_app_account': 'Return to an App Account?',
      'receive_into_my_pocket': 'RECEIVE INTO (MY POCKET)',
      'return_to_their_pocket': 'RETURN TO (THEIR POCKET)',
      'current': 'Current',
      'delete_loan': 'Delete Loan?',
      'delete_loan_message': 'This will revert all balances and delete this loan forever.',
      'loan_reminder_message': 'Hey {name}! Just a gentle reminder regarding the loan balance of ৳{amount} when you get a moment. Thank you!',
      'installment_number': 'Installment #{number}',
      'due': 'Due',
      'money_you_gave': 'Money you gave',
      'money_you_took': 'Money you took',
      'total_amount': 'Total Amount',
      'delete_payment': 'Delete Payment?',
      'delete_payment_message': 'This will restore the loan balance and revert account changes.',
      'name': 'Name',
      'receive_payment': 'Receive Payment',
      'repay_loan': 'Repay Loan',
    
      // Dashboard
      'recent_transactions': 'Recent Transactions',
      'goals': 'Goals',
      'advisor_update': 'Advisor Update',
      'loan_taken': 'Loan Taken',
      'bills': 'Bills',
      'me': 'Me',
      'quick_actions': 'Quick Actions',
      'savings_and_loans': 'Savings & Loans',
      'taken': 'Taken',
      'budget_warning': 'Budget Warning!',
      'upcoming_bill_due': 'Upcoming Bill Due',
      'set_goal': 'Set Goal',
      'adjust_goals': 'Adjust Goals',
      'set_your_goals': 'Set Your Goals',
      'records': 'Records',
      'overdue_bills_alert': 'Overdue Bills Alert',
      'view_trends': 'View Trends',
      'good_morning': 'Good Morning',
      'bill_due_today': 'Bill Due Today',
      'savings_alert': 'Savings Alert',
      'view_analytics': 'View Analytics',
      'good_afternoon': 'Good Afternoon',
      'good_evening': 'Good Evening',
      'received': 'Received',
      'smart': 'Smart',
      'category_spike': 'Category Spike!',
      'excellent_cashflow': 'Excellent Cashflow!',
      'track_your_income_and_expense_targets': 'Track your income & expense targets',
      'budget_exceeded': 'Budget Exceeded!',
      'log_savings': 'Log Savings',
      'loan_given': 'Loan Given',
      'credit': 'Credit',
      'savings': 'Savings',
},
    'bn': {
      // Login Screen
      'welcome_back': 'পুনরায় স্বাগতম!',
      'login_subtitle': 'আপনার হিসাব-নিকাশ পরিচালনা করতে সাইন ইন করুন',
      'email': 'ইমেইল',
      'email_hint': 'আপনার ইমেইল লিখুন',
      'password': 'পাসওয়ার্ড',
      'password_hint': 'আপনার পাসওয়ার্ড লিখুন',
      'sign_in': 'সাইন ইন করুন',
      'no_account': 'অ্যাকাউন্ট নেই? ',
      'sign_up_now': 'অ্যাকাউন্ট তৈরি করুন',
      'email_required': 'ইমেইল ঠিকানা আবশ্যক',
      'password_required': 'পাসওয়ার্ড আবশ্যক',
      'invalid_credentials': 'ইমেইল বা পাসওয়ার্ড সঠিক নয়',
      'login_failed': 'সাইন ইন করা যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।',

      // Signup Screen
      'create_account': 'অ্যাকাউন্ট তৈরি করুন',
      'signup_subtitle': 'নিজের টাকা-পয়সার নিয়ন্ত্রণ শুরু করুন',
      'full_name': 'সম্পূর্ণ নাম',
      'confirm_password': 'পাসওয়ার্ড নিশ্চিত করুন',
      'already_have_account': 'ইতিমধ্যেই একটি অ্যাকাউন্ট আছে? ',
      
      // Nav Bar
      'home': 'হোম',
      'wallet': 'ওয়ালেট',
      'stats': 'পরিসংখ্যান',

      // Profile Screen
      'profile': 'প্রোফাইল',
      'edit_profile': 'প্রোফাইল সম্পাদনা',
      'account_settings': 'অ্যাকাউন্ট সেটিংস',
      'language': 'ভাষা (Language)',
      'dark_mode': 'ডার্ক মোড',
      'biometric_lock': 'বায়োমেট্রিক লক',
      'help_support': 'সাহায্য ও সাপোর্ট',
      'about_app': 'অ্যাপ সম্পর্কে',
      'log_out': 'লগ আউট',
      'confirm_logout': 'লগ আউট নিশ্চিত করুন',
      'logout_message': 'আপনি কি নিশ্চিত যে আপনি লগ আউট করতে চান?',
      'cancel': 'বাতিল',
      'user_details_error': 'ব্যবহারকারীর তথ্য লোড করা যায়নি',
      'account_information': 'অ্যাকাউন্টের তথ্য',
      'account_name': 'অ্যাকাউন্টের নাম',
      'active_timelines': 'সক্রিয় সময়সীমা',
      'ai_wealth_copilot': 'এআই ওয়েলথ কো-পাইলট',
      'amount': 'পরিমাণ',
      'account_name_1': 'অ্যাকাউন্টের নাম',
      'account_number': 'অ্যাকাউন্ট নম্বর',
      'account_name_eg_savings': 'অ্যাকাউন্টের নাম (যেমন: DPS, বিকাশ)',
      'add_money': 'টাকা যোগ করুন',
      'accountwise_distribution': 'অ্যাকাউন্টভিত্তিক বণ্টন',
      'accounts': 'অ্যাকাউন্ট',
      'add_account': 'অ্যাকাউন্ট যোগ করুন',
      'add_card': 'কার্ড যোগ করুন',
      'add_a_credit_card': 'ব্যালেন্স, বিল ও নির্ধারিত তারিখ ট্র্যাক করতে একটি ক্রেডিট কার্ড যোগ করুন।',
      'add_a_note': 'একটি নোট যোগ করুন...',
      'add_a_savings_account': 'প্রথমে একটি সেভিংস অ্যাকাউন্ট যোগ করুন!',
      'add_amounts_done_before': 'এই মাসে অ্যাপ ব্যবহারের আগে হওয়া পরিমাণ যোগ করুন',
      'add_an_account_to': 'আপনার সম্পদের হিসাব দেখতে একটি অ্যাকাউন্ট যোগ করুন',
      'add_your_recurring_bills': 'নিয়মিত বিল, সাবস্ক্রিপশন বা ইউটিলিটি পেমেন্ট যোগ করুন, যাতে কোনো নির্ধারিত তারিখ মিস না হয়।',
      'add_to_savings': 'সঞ্চয়ে যোগ করুন',
      'adjust_account_balance': 'অ্যাকাউন্টের ব্যালেন্স সমন্বয় করুন',
      'all': 'সব',
      'all_caught_up': 'সব ঠিক আছে!',
      'all_scheduled_subscriptions_and': 'সব নির্ধারিত সাবস্ক্রিপশন ও পুনরাবৃত্ত পেমেন্ট একসাথে',
      'already_paiddeducted': 'ইতোমধ্যে পরিশোধ বা কাটা হয়েছে?',
      'app_locked': 'অ্যাপ লক করা আছে',
      'apply': 'প্রয়োগ করুন',
      'are_you_sure_you': 'আপনি কি নিশ্চিতভাবে এই ক্রেডিট কার্ডটি মুছে ফেলতে চান? এই কাজটি আর ফিরিয়ে আনা যাবে না।',
      'are_you_sure_you_1': 'আপনি কি নিশ্চিতভাবে এই পুনরাবৃত্ত বিলটি মুছে ফেলতে চান? আগের পেমেন্ট রেকর্ড মুছে যাবে না।',
      'available_credit': 'উপলব্ধ ক্রেডিট',
      'available_limit': 'উপলব্ধ সীমা',
      'all_bank_details': 'ব্যাংকের সব বিবরণ',
      'all_time': 'সব সময়',
      'bank': 'ব্যাংক',
      'bank_account_details': 'ব্যাংক অ্যাকাউন্টের বিবরণ',
      'branch_name': 'শাখার নাম',
      'card_payment': 'কার্ড পেমেন্ট',
      'combined_portfolio_balance': 'সম্মিলিত পোর্টফোলিও ব্যালেন্স',
      'copy_all': 'সব কপি',
      'copied_to_clipboard': '{label} ক্লিপবোর্ডে কপি হয়েছে!',
      'card_color_theme': 'কার্ডের রঙের থিম',
      'card_details': 'কার্ডের বিবরণ',
      'card_network': 'কার্ড নেটওয়ার্ক',
      'card_number': 'কার্ড নম্বর',
      'card_number_eg_last': 'কার্ড নম্বর (উদাঃ শেষ ৪ সংখ্যা)',
      'card_number_last_4': 'কার্ড নম্বর (শেষ ৪ সংখ্যা বা সম্পূর্ণ)',
      'card_not_found': 'কার্ড পাওয়া যায়নি',
      'category': 'ক্যাটাগরি',
      'category_subtitle': 'এটি কোন ধরনের লেনদেন?',
      'category_manager': 'ক্যাটাগরি ম্যানেজার',
      'category_type': 'ক্যাটাগরির ধরন',
      'change': 'পরিবর্তন',
      'choose_how_you_want': 'কীভাবে তারিখ ফিল্টার করতে চান তা নির্বাচন করুন',
      'confirm': 'নিশ্চিত করুন',
      'confirm_sign_out': 'সাইন আউট নিশ্চিত করুন',
      'confirm_transaction': 'লেনদেন নিশ্চিত করুন',
      'copy_reminder_template': 'রিমাইন্ডার টেমপ্লেট কপি করুন',
      'create_subscription': 'সাবস্ক্রিপশন তৈরি করুন',
      'credit_cards': 'ক্রেডিট কার্ডসমূহ',
      'credit_card_payment': 'ক্রেডিট কার্ড পেমেন্ট',
      'deduct_from_account': 'অ্যাকাউন্ট থেকে কাটুন',
      'deduct_from': 'যেখান থেকে কাটবে',
      'delete': 'মুছে ফেলুন',
      'delete_card': 'কার্ড মুছে ফেলুন',
      'delete_category': 'ক্যাটাগরি মুছে ফেলবেন?',
      'delete_subscription': 'সাবস্ক্রিপশন মুছে ফেলবেন?',
      'destination': 'গন্তব্য',
      'destination_card': 'গন্তব্য কার্ড',
      'destination_member': 'গন্তব্য সদস্য',
      'destination_subtitle': 'টাকাটি কোথায় যাচ্ছে?',
      'divide_into_installments': 'কিস্তিতে ভাগ করুন',
      'due_in': 'বাকি',
      'edit_account_info': 'অ্যাকাউন্টের তথ্য সম্পাদনা করুন',
      'edit_card': 'কার্ড সম্পাদনা করুন',
      'edit_person_name': 'ব্যক্তির নাম সম্পাদনা করুন',
      'error': 'ত্রুটি',
      'error_loading_transactions': 'লেনদেন লোড করতে সমস্যা হয়েছে',
      'enter_your_4digit_security': 'আপনার ৪-সংখ্যার সিকিউরিটি পিন দিন',
      'expense': 'খরচ',
      'frequency': 'পুনরাবৃত্তি',
      'full_balance': 'পূর্ণ ব্যালেন্স',
      'filter_transactions': 'লেনদেন ফিল্টার করুন',
      'for_security_do_not': 'নিরাপত্তার স্বার্থে পিন, সিভিভি বা পাসওয়ার্ড দিবেন না।',
      'forgot_security_pin': 'সিকিউরিটি পিন ভুলে গেছেন?',
      'frequency_1': 'পুনরাবৃত্তি',
      'given_by': 'দিয়েছেন',
      'initial_progress_already_done': 'প্রাথমিক অগ্রগতি (ইতোমধ্যে সম্পন্ন)',
      'installment_timeline': 'কিস্তির সময়সীমা',
      'installments': 'কিস্তি',
      'income': 'আয়',
      'load_more': 'আরও লোড করুন',
      'loan_details': 'ঋণের বিস্তারিত বিবরণ',
      'loans': 'ঋণ',
      'member_breakdown': 'সদস্যভিত্তিক বিশ্লেষণ',
      'mobile_wallet_details': 'মোবাইল ওয়ালেটের বিস্তারিত বিবরণ',
      'mobile_number': 'মোবাইল নম্বর',
      'monthly_analytics': 'মাসিক বিশ্লেষণ',
      'monthly_budget_health': 'মাসিক বাজেট স্বাস্থ্য',
      'monthly_estimated_dues': 'মাসিক সম্ভাব্য বকেয়া',
      'monthly_goals': 'মাসিক লক্ষ্য',
      'monthly_sheet_copied_to': 'মাসিক শিট সিএসভি হিসেবে ক্লিপবোর্ডে কপি করা হয়েছে!',
      'month_short_1': 'জানু',
      'month_short_2': 'ফেব',
      'month_short_3': 'মার্চ',
      'month_short_4': 'এপ্রি',
      'month_short_5': 'মে',
      'month_short_6': 'জুন',
      'month_short_7': 'জুল',
      'month_short_8': 'আগ',
      'month_short_9': 'সেপ',
      'month_short_10': 'অক্টো',
      'month_short_11': 'নভে',
      'month_short_12': 'ডিসে',
      'my_savings': 'আমার সঞ্চয়',
      'new_account': 'নতুন অ্যাকাউন্ট',
      'new_loan': 'নতুন ঋণ',
      'new_savings_account': 'নতুন সঞ্চয় অ্যাকাউন্ট',
      'new_subscription': 'নতুন সাবস্ক্রিপশন',
      'next_due_date': 'পরবর্তী নির্ধারিত তারিখ',
      'next_statement': 'পরবর্তী স্টেটমেন্ট',
      'no_credit_cards_yet': 'কোনো ক্রেডিট কার্ড নেই',
      'no_subscriptions_yet': 'কোনো সাবস্ক্রিপশন নেই',
      'no_transactions_found': 'কোনো লেনদেন পাওয়া যায়নি',
      'no_categories_found': 'কোনো ক্যাটাগরি পাওয়া যায়নি',
      'no_loans_found': 'কোনো ঋণ পাওয়া যায়নি',
      'no_recent_transactions': 'কোনো সাম্প্রতিক লেনদেন নেই',
      'no_repayments_yet': 'কোনো পরিশোধ করা হয়নি।',
      'no_transactions_recorded_yet': 'এখনও কোনো লেনদেন রেকর্ড করা হয়নি',
      'no_transactions_to_export': 'এই মাসের জন্য এক্সপোর্ট করার মতো কোনো লেনদেন নেই',
      'no_vaults_found_tap': 'কোনো সঞ্চয় ভল্ট পাওয়া যায়নি। প্রথম ভল্ট তৈরি করতে অ্যাকাউন্ট যোগ করুন।',
      'none_outside_app': 'কিছুই না (অ্যাপের বাইরে)',
      'note_optional': 'নোট (ঐচ্ছিক)',
      'note_optional_1': 'নোট (ঐচ্ছিক)',
      'notifications': 'নোটিফিকেশন',
      'note': 'নোট',
      'notes': 'নোট',
      'notes_subtitle': 'অতিরিক্ত তথ্য যোগ করুন',
      'owner_share_distribution': 'মালিকানার শেয়ার বন্টন',
      'owner_split': 'মালিকানা বিভাজন',
      'outstanding': 'বকেয়া',
      'opening_balance': 'শুরুর ব্যালেন্স',
      'others': 'অন্যান্য',
      'pay_log': 'পেমেন্ট করে রেকর্ড করুন',
      'pay_bill': 'বিল পরিশোধ করুন',
      'payment_due': 'পেমেন্ট বাকি',
      'payment_recieved': 'পেমেন্ট গ্রহণ হয়েছে',
      'payment_cannot_exceed_remaining': 'পেমেন্ট বাকি পরিমাণের চেয়ে বেশি হতে পারে না',
      'paying_bill_for': 'যে বিল পরিশোধ হচ্ছে',
      'person_name_eg_rahim': 'ব্যক্তির নাম (উদাঃ রহিম)',
      'please_enter_account_name': 'অনুগ্রহ করে অ্যাকাউন্টের নাম লিখুন',
      'please_enter_amount': 'অনুগ্রহ করে পরিমাণ লিখুন',
      'please_enter_an_amount': 'অনুগ্রহ করে একটি পরিমাণ লিখুন',
      'please_enter_name_and': 'অনুগ্রহ করে নাম ও পরিমাণ লিখুন',
      'please_select_destination_account': 'অনুগ্রহ করে গন্তব্য অ্যাকাউন্ট নির্বাচন করুন',
      'please_select_payment_source': 'অনুগ্রহ করে পেমেন্টের উৎস নির্বাচন করুন',
      'repayment_reminder_template': 'পরিশোধের রিমাইন্ডার টেমপ্লেট',
      'reminder_template_copied': 'রিমাইন্ডার টেমপ্লেট কপি করা হয়েছে!',
      'repayment_history': 'পরিশোধের ইতিহাস',
      'routing_number': 'রাউটিং নম্বর',
      'save': 'সংরক্ষণ করুন',
      'save_card': 'কার্ড সংরক্ষণ করুন',
      'save_changes': 'পরিবর্তনগুলো সংরক্ষণ করুন',
      'save_loan': 'ঋণ সংরক্ষণ করুন',
      'save_transaction': 'লেনদেন সংরক্ষণ করুন',
      'savings_dashboard': 'সঞ্চয় ড্যাশবোর্ড',
      'search_by_note_category': 'নোট, ক্যাটাগরি, বা পরিমাণ দিয়ে খুঁজুন...',
      'search_by_person_name': 'ব্যক্তির নাম বা নোট দিয়ে খুঁজুন...',
      'secure_savings_vault': 'নিরাপদ সঞ্চয় ভল্ট',
      'see_all': 'সবগুলো দেখুন',
      'select_account': 'অ্যাকাউন্ট নির্বাচন করুন',
      'select_account_optional': 'অ্যাকাউন্ট নির্বাচন করুন (ঐচ্ছিক)',
      'select_color': 'রঙ নির্বাচন করুন',
      'select_custom_date_range': 'কাস্টম তারিখের পরিসর নির্বাচন করুন',
      'select_custom_date_range_subtitle': 'শুরুর ও শেষের নির্দিষ্ট তারিখ বেছে নিন',
      'select_icon': 'আইকন নির্বাচন করুন',
      'select_month_year': 'মাস এবং বছর নির্বাচন করুন',
      'select_specific_month_year': 'নির্দিষ্ট মাস ও বছর নির্বাচন করুন',
      'select_specific_month_year_subtitle': 'যেকোনো নির্দিষ্ট মাস দিয়ে ফিল্টার করুন',
      'set_monthly_targets': 'মাসিক লক্ষ্য নির্ধারণ করুন',
      'set_income_targets_and': 'আপনার সঞ্চয়ের সম্ভাবনা ও আর্থিক অবস্থার বিস্তারিত ধারণা পেতে আয়ের লক্ষ্য এবং খরচের সীমা নির্ধারণ করুন।',
      'seyam_ali': 'সিয়াম আলী',
      'self': 'নিজে',
      'show_all_time': 'সব সময় দেখান',
      'show_all_time_subtitle': 'তারিখ ফিল্টার সরিয়ে সব লেনদেন দেখান',
      'source': 'উৎস',
      'source_member': 'উৎস সদস্য',
      'source_subtitle': 'টাকাটি কোথা থেকে আসছে?',
      'split_this_loan_into': 'এই ঋণটি ছোট ছোট পেমেন্টে ভাগ করুন',
      'subscriptions_bills': 'সাবস্ক্রিপশন এবং বিল',
      'total_assets': 'মোট সম্পদ',
      'total_balance': 'মোট ব্যালেন্স',
      'total_expense': 'মোট খরচ',
      'total_income': 'মোট আয়',
      'transaction_history': 'লেনদেনের ইতিহাস',
      'tap_the_add_button': 'লেনদেন যোগ করতে Add বোতামে চাপুন',
      'target_settings': 'লক্ষ্য সেটিংস',
      'this_month': 'এই মাস',
      'this_month_subtitle': 'চলতি মাসের লেনদেন দেখান',
      'this_week': 'এই সপ্তাহ',
      'this_week_subtitle': 'গত ৭ দিনের লেনদেন দেখান',
      'to_protect_your_personal': 'আপনার ব্যক্তিগত লেজার সুরক্ষিত রাখতে পিন বন্ধ বা রিসেট করার আগে অ্যাকাউন্ট থেকে সাইন আউট করে পাসওয়ার্ড দিয়ে আবার লগ ইন করতে হবে।',
      'to_owner': 'যার কাছে',
      'total_balance_1': 'মোট ব্যালেন্স',
      'total_net_savings': 'মোট নিট সঞ্চয়',
      'track_your_income_expense': 'আপনার আয় ও খরচের লক্ষ্য ট্র্যাক করুন',
      'transactions': 'লেনদেন',
      'transfer': 'ট্রান্সফার',
      'trends_summary': 'ট্রেন্ডের সারাংশ',
      'tx_type': 'লেনদেনের ধরন',
      'update_targets': 'লক্ষ্য আপডেট করুন',
      'wallet_mobile_number': 'ওয়ালেটের মোবাইল নম্বর',
      'wallet_details': 'ওয়ালেটের বিবরণ',
      'wallet_name': 'ওয়ালেটের নাম',
      'where_is_my_money': 'আমার টাকা কোথায়?',
      'who_is_receiving': 'কে গ্রহণ করছেন?',
      'who_is_sending': 'কে পাঠাচ্ছেন?',
      'withdraw': 'টাকা তুলুন',
      'your_savings_vaults': 'আপনার সঞ্চয় ভল্টসমূহ',
      'you_have_no_pending': 'আপনার কোনো পেন্ডিং অ্যালার্ট বা আসন্ন পেমেন্ট নেই।',
      'eg_dbbl_bkash_my': 'উদাঃ ডিবিবিএল, বিকাশ, মাই ওয়ালেট',
      'track_money_stay_in': '— টাকা ট্র্যাক করুন। নিয়ন্ত্রণ রাখুন। —',
      'combined_balance_of_all': '“সব এমএফএস, ব্যাংক ও নগদ অ্যাকাউন্টের সম্মিলিত ব্যালেন্স”',
      'given_total': 'মোট দেওয়া',
      'taken_total': 'মোট নেওয়া',
      'pending': 'বাকি',
      'given': 'দেওয়া',
      'by_person': 'ব্যক্তি অনুযায়ী',
      'settled': 'মিটে গেছে',
      'they_owe': 'সে দেবে',
      'you_owe': 'আপনি দেবেন',
      'given_pending': 'দেওয়া (বাকি)',
      'taken_pending': 'নেওয়া (বাকি)',
      'net_balance': 'নিট ব্যালেন্স',
      'loan_count_one': '{count}টি ঋণ',
      'loan_count_many': '{count}টি ঋণ',
      'paid': 'পরিশোধিত',
      'total_given': 'মোট দেওয়া',
      'total_taken': 'মোট নেওয়া',
      'paid_back': 'ফেরত পাওয়া',
      'remaining': 'বাকি',
      'person_name': 'ব্যক্তির নাম',
      'loan_owner_portion': 'ঋণের মালিক / অংশ',
      'link_account_optional': 'অ্যাকাউন্ট লিংক করুন (ঐচ্ছিক)',
      'given_loan': 'দেওয়া ঋণ',
      'taken_loan': 'নেওয়া ঋণ',
      'balance_update_on': 'চালু - এখনই ব্যালেন্স আপডেট হবে',
      'balance_update_off': 'বন্ধ - শুধু ঋণ রেকর্ড হবে (ব্যালেন্স আগে থেকেই ঠিক আছে)',
      'weekly': 'সাপ্তাহিক',
      'monthly': 'মাসিক',
      'installment_times': '{count} বার',
      'installment_summary': 'এই ঋণটি {count}টি কিস্তিতে ভাগ হবে, প্রতি কিস্তি ৳{amount}, {frequency} পরিশোধ।',
      'receive_from': '{name} থেকে গ্রহণ করুন',
      'repay_to': '{name}-কে পরিশোধ করুন',
      'money_added_to_account': 'টাকা আপনার অ্যাকাউন্টে যোগ হবে',
      'record_money_movement': 'টাকা কোথায় যাচ্ছে তা রেকর্ড করুন',
      'amount_max': 'পরিমাণ (সর্বোচ্চ: {amount})',
      'repay_from_my_pocket': 'পরিশোধের উৎস (আমার পকেট)',
      'add_to_my_app_account': 'আমার অ্যাপ অ্যাকাউন্টে যোগ করবেন?',
      'return_to_app_account': 'অ্যাপ অ্যাকাউন্টে ফেরত দেবেন?',
      'receive_into_my_pocket': 'গ্রহণের গন্তব্য (আমার পকেট)',
      'return_to_their_pocket': 'ফেরত দিন (তাদের পকেটে)',
      'current': 'বর্তমান',
      'delete_loan': 'ঋণ মুছে ফেলবেন?',
      'delete_loan_message': 'এতে সব ব্যালেন্স আগের অবস্থায় ফিরবে এবং এই ঋণটি স্থায়ীভাবে মুছে যাবে।',
      'loan_reminder_message': 'হ্যালো {name}! ঋণের বাকি ব্যালেন্স ৳{amount} নিয়ে একটি ছোট রিমাইন্ডার দিলাম। সময় হলে জানাবেন। ধন্যবাদ!',
      'installment_number': 'কিস্তি #{number}',
      'due': 'শেষ তারিখ',
      'money_you_gave': 'আপনি যে টাকা দিয়েছেন',
      'money_you_took': 'আপনি যে টাকা নিয়েছেন',
      'total_amount': 'মোট পরিমাণ',
      'delete_payment': 'পেমেন্ট মুছে ফেলবেন?',
      'delete_payment_message': 'এতে ঋণের ব্যালেন্স ফিরবে এবং অ্যাকাউন্টের পরিবর্তনও আগের অবস্থায় যাবে।',
      'name': 'নাম',
      'receive_payment': 'পেমেন্ট গ্রহণ করুন',
      'repay_loan': 'ঋণ পরিশোধ করুন',
    
      // Dashboard
      'recent_transactions': 'সাম্প্রতিক লেনদেন',
      'goals': 'লক্ষ্যসমূহ',
      'advisor_update': 'পরামর্শ আপডেট',
      'loan_taken': 'গৃহীত ঋণ',
      'bills': 'বিলসমূহ',
      'me': 'আমি',
      'quick_actions': 'দ্রুত অ্যাকশন',
      'savings_and_loans': 'সঞ্চয় ও ঋণ',
      'taken': 'গৃহীত',
      'budget_warning': 'বাজেট সতর্কতা!',
      'upcoming_bill_due': 'আসন্ন বিলের তারিখ',
      'set_goal': 'লক্ষ্য নির্ধারণ করুন',
      'adjust_goals': 'লক্ষ্য সামঞ্জস্য করুন',
      'set_your_goals': 'আপনার লক্ষ্য নির্ধারণ করুন',
      'records': 'হিসাব',
      'overdue_bills_alert': 'বকেয়া বিল সতর্কতা',
      'view_trends': 'ট্রেন্ড দেখুন',
      'good_morning': 'শুভ সকাল',
      'bill_due_today': 'আজ বিল পরিশোধের দিন',
      'savings_alert': 'সঞ্চয় সতর্কতা',
      'view_analytics': 'বিশ্লেষণ দেখুন',
      'good_afternoon': 'শুভ অপরাহ্ন',
      'good_evening': 'শুভ সন্ধ্যা',
      'received': 'পেয়েছেন',
      'smart': 'স্মার্ট',
      'category_spike': 'ক্যাটাগরিতে হঠাৎ বেশি খরচ!',
      'excellent_cashflow': 'দারুণ ক্যাশফ্লো!',
      'track_your_income_and_expense_targets': 'আপনার আয় ও খরচের লক্ষ্য ট্র্যাক করুন',
      'budget_exceeded': 'বাজেট ছাড়িয়ে গেছে!',
      'log_savings': 'সঞ্চয় লগ করুন',
      'loan_given': 'দেওয়া ঋণ',
      'credit': 'ক্রেডিট',
      'savings': 'সঞ্চয়',
}
  };

  static String get(String key) {
    final String langCode = LanguageService().currentLanguage;
    return _localizedValues[langCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }

  static String convertDigits(String input) {
    if (LanguageService().currentLanguage != 'bn') return input;
    const englishToBengaliDigits = {
      '0': '০',
      '1': '১',
      '2': '২',
      '3': '৩',
      '4': '৪',
      '5': '৫',
      '6': '৬',
      '7': '৭',
      '8': '৮',
      '9': '৯',
    };
    return input.replaceAllMapped(RegExp(r'[0-9]'), (match) {
      return englishToBengaliDigits[match.group(0)!]!;
    });
  }
}
